name: Tatum PHP SDK
markdown: kramdown
kramdown:
  entity_output: :as_input
  parse_block_html: true
  parse_span_html: true
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: table
    bold_every: 5
